version: '3.6'
services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  postgres2:
    image: postgres:14
    restart: always
    volumes:
      - db_data2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  postgres3:
    image: postgres:14
    restart: always
    volumes:
      - db_data3:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  postgres4:
    image: postgres:14
    restart: always
    volumes:
      - db_data4:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  centos-java-hasura:
    build:
      context: ./
      dockerfile: Dockerfile.combined-java-centos
    depends_on:
      - "postgres4"    
    ports:
      - 8061:8080
      - 8082:8081
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres4:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres4:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  centos-athena-hasura:
    build:
      context: ./
      dockerfile: Dockerfile.combined-athena-centos
    depends_on:
      - "postgres3"
    restart: always
    ports:
      - 8085:8080
      - 3001:3000
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres3:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres3:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      PORT: 3000
      # URL to this backend service, as seen from the Hasura service
      SERVER_ENDPOINT: http://0.0.0.0:3000
      # URL to the Hasura instance, as seen from this service
      HASURA_ENDPOINT: http://0.0.0.0:8080
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # Catalog name for AthenaSQL data, DEFAULT: "AwsDataCatalog"
      AWS_ATHENA_CATALOG_NAME: ${AWS_ATHENA_CATALOG_NAME}
      # DB name to connect to, will be introspected
      # and used to generate Hasura's metadata + GraphQL Schema
      AWS_ATHENA_DB_NAME: ${AWS_ATHENA_DB_NAME}
      # S3 URL to bucket in which to store query results
      # EXAMPLE: s3://athena-demo-bucket-hasura-gavin/query-results
      AWS_S3_RESULT_BUCKET_ADDRESS: ${AWS_S3_RESULT_BUCKET_ADDRESS}

  combined-java-spring:
    build:
      context: ./
      dockerfile: Dockerfile.combined-spring
    ports:
      - 8060:8080
      - 8081:8081
    depends_on:
      - "postgres2"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres2:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres2:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  combined:
    build:
      context: ./
      dockerfile: Dockerfile.combined
    ports:
      - 8080:8080
      - 3000:3000
    depends_on:
      - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      PORT: 3000
      # URL to this backend service, as seen from the Hasura service
      SERVER_ENDPOINT: http://0.0.0.0:3000
      # URL to the Hasura instance, as seen from this service
      HASURA_ENDPOINT: http://0.0.0.0:8080
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # Catalog name for AthenaSQL data, DEFAULT: "AwsDataCatalog"
      AWS_ATHENA_CATALOG_NAME: ${AWS_ATHENA_CATALOG_NAME}
      # DB name to connect to, will be introspected
      # and used to generate Hasura's metadata + GraphQL Schema
      AWS_ATHENA_DB_NAME: ${AWS_ATHENA_DB_NAME}
      # S3 URL to bucket in which to store query results
      # EXAMPLE: s3://athena-demo-bucket-hasura-gavin/query-results
      AWS_S3_RESULT_BUCKET_ADDRESS: ${AWS_S3_RESULT_BUCKET_ADDRESS}

volumes:
  db_data: ~
  db_data2: ~
  db_data3: ~
  db_data4: ~
  notused: ~
